account/urls.py
from django.urls import path

from . import views


app_name='account'
urlpatterns = [
    path('logout/', views.Logout, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
    path('submit-newsletter-form/', views.newletter_submit, name='newsletter-submit'),
    
    path("activate/<slug:uidb64>/<slug:token>/", views.activate_email, name="activate"),

    path('reset/<uidb64>/<token>/', views.ResetPasswordVerify.as_view(), name='password_reset_confirm'),

]

boni/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('mainapp.urls')),
    path('events/', include('events.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views


app_name='events'
urlpatterns = [
    path('add/', views.CreateEvent.as_view(), name='add-event'),
    path('edit/<str:uid>/', views.UpdateEvent.as_view(), name='event-update'),
    path('duplicate/<str:uid>/', views.duplicate_event, name='event-duplicate'),
    path('detail/<str:slug>/', views.EventDetail.as_view(), name='event-detail'),
    
    path('search/', views.EventSearch.as_view(), name='event-search'),
    path('calendar/', views.EventCalendarView.as_view(), name='event-calendar'),
    path('my-events/', views.MyEvent.as_view(), name='my-event'),
    path('add-calendar/<str:uid>/', views.add_event_to_calendar, name='add-calendar'),
    path('events/organizer/<str:uid>/', views.OrganizerEvents.as_view(), name='organizer-events'),
    # path('events/my_tickets/', views.UserEventTickets.as_view(), name='my-tickets'),
    # path('order/tickets/<str:uid>', views.order_ticket, name='order-ticket'),

    path('save/<str:uid>/', views.add_event_to_saved, name='save-event'),
    path('saved/', views.SavedEvents.as_view(), name='saved-events'),
    # path('report/<str:uid>/', views.report_event_now, name='report-events'),

    path('events/registered_teams/', views.RegisteredTeams.as_view(), name='registered-teams'),
    
    path('trip_advisor/', views.get_trips_view, name='trip-advisor'),

]

events/forms.py
from ckeditor.widgets import CKEditorWidget

from django import forms
from django.utils import timezone
from django.core.validators import validate_email, RegexValidator
from django.contrib.auth import password_validation
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.hashers import check_password

from django.forms import fields
from django.forms import formset_factory
from django.shortcuts import get_object_or_404

from .models import Event, UserTicket
from .utils import convert_str_date


class UserTicketForm(forms.ModelForm):
    class Meta:
        model = UserTicket
        fields = '__all__'
       
        
class ReviewForm(forms.Form):
    stars = forms.IntegerField()
    comment = forms.CharField(max_length=800)

class EventForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Event
        fields = '__all__'
        exclude = ('slug',)


phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

class ContactForm(forms.Form):
    name = forms.CharField(max_length=25, required=False)
    phone = forms.CharField(max_length=17, required=False, validators=[phone_regex])
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()

events/views.py
import random
import json
from typing import List
import uuid

from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models.query_utils import Q
from django.forms import formset_factory
from django.contrib import messages
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import logout,authenticate,login
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.utils.encoding import force_text,force_bytes
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.http import JsonResponse

from account.models import Profile, User
from mainapp.mixins import ajax_autocomplete

from .models import (Amenity, Event, EventReview, EventSave,
    EventView, Gallery, Category, ReviewImage, EventCalendar,
    UserTicket, EventReport)
from .forms import EventForm, ReviewForm, UserTicketForm, ContactForm
from .utils import convert_str_date, get_valid_ip, get_trip_advisor



class RegisteredTeams(LoginRequiredMixin, ListView):
    template_name = 'events/registered_teams.html'
    extra_context = {
        'title': 'Registered Teams'
    }
    model = Event
    context_object_name = 'events'
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


def get_trips_view(request):
    if request.is_ajax():
        trips = []

        # Get the event id
        uid = request.GET.get('id')

        try:
            event = Event.objects.get(uid=uid)

            # Get the trips
            trips = get_trip_advisor(event.location)

            
        except Exception as e:
            print(e)
            pass

        return JsonResponse(data={'results': trips}, status=200)

    return redirect('mainapp:home')


class EventSearch(ListView):
    template_name = 'events/search-map-right.html'
    extra_context = {
        'title': 'Event Search'
    }
    model = Event
    context_object_name = 'events'

    def object_list(self):
        return self.get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories_set = Category.objects.all()
        queryset = self.model.objects.all()

        context["events"] = queryset[:10]
        context["category"] = categories_set

        # Send sets to context
        context['all_events'] = queryset
        context['all_categories'] = categories_set
        
        return context
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data()

        response = ajax_autocomplete(request, context)
        if response is not None:
            return response

        # Check for query strings
        search = request.GET.get('search')
        if search:
            queryset = self.get_queryset()
            search_input = request.GET.get('search-input')
            if search_input:
                # Search location
                queryset = queryset.filter(location__icontains=search_input)
                context['searchInput'] = search_input

            search_tcd = request.GET.get('search-tcd')
            if search_tcd:
                # Search decription and title
                queryset = queryset.filter(
                    Q(title__icontains=search_tcd) | Q(description__icontains=search_tcd) | Q(category__name__iexact=search_tcd)
                )
                context['search_tcd'] = search_tcd
            
            category = request.GET.get('category')
            if category:
                queryset = queryset.filter(category__id=category)
                context['searchCategory'] = int(category)
            # else:
            #     # Search for category
            #     if search_tcd:
            #         queryset = queryset.filter(category__name__iexact=search_tcd)

            start_time = request.GET.get('start_time')
            if start_time:
                context['start_time'] = start_time
                # Convert to datetime
                start_time = convert_str_date(start_time)
                queryset = queryset.filter(start_date__gte = start_time)
            
            end_time = request.GET.get('end_time')
            if end_time:
                context['end_time'] = end_time
                # Convert to datetime
                end_time = convert_str_date(end_time)
                queryset = queryset.filter(end_date__lte = end_time)

            # Sort the queryset
            sort = request.GET.get('sort')
            if sort:
                if sort == 'most_viewed':
                    queryset = queryset.order_by('-views')
                elif sort == 'most_recent':
                    queryset = queryset.order_by('-created')
                elif sort == 'most_liked':
                    queryset = queryset.order_by('-likes')

            
            context[self.context_object_name] = queryset

        return render(request, self.template_name, context)
    

class EventCalendarView(LoginRequiredMixin, ListView):
    template_name = 'events/event-calendar.html'
    extra_context = {
        'title': 'Event Calendar'
    }
    model = EventCalendar
    context_object_name = 'events'
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class UserEventTickets(LoginRequiredMixin, ListView):
    template_name = 'events/tickets.html'
    extra_context = {
        'title': 'Ticket Orders'
    }
    model = UserTicket
    context_object_name = 'tickets'
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)



from django.http import HttpResponse


from django_xhtml2pdf.utils import generate_pdf

def order_ticket(request, uid):
    resp = HttpResponse(content_type='application/pdf')
    
    ticket = get_object_or_404(UserTicket, uid=uid)

    context = {
        'ticket': ticket,
        'pagesize':'A4'
    }

    result = generate_pdf('events/ticket.html', file_object=resp, context=context)
    return result



class EventDetail(DetailView):
    template_name = 'events/event-detail.html'
    extra_context = {
        'title': 'Event Detail'
    }
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    model = Event

    def get_object(self):
        query = { self.slug_field : self.kwargs.get(self.slug_url_kwarg)}
        self.object = get_object_or_404(Event, **query)
        return self.object

    def get_context_data(self, **kwargs):
        self.get_object()

        context = super().get_context_data(**kwargs)
        context["title"] = self.object.title

        context['gallery'] = self.object.gallery_set.all()
        context['reviews'] = self.object.eventreview_set.all()

        valid_events_id_list = Event.objects.filter(published=True, user__active=True).values_list('id', flat=True)
        random_event_id_list = random.sample(list(valid_events_id_list), min(len(valid_events_id_list), 10))
        context['related_events'] = Event.objects.filter(id__in=random_event_id_list)

        context['review_form'] = ReviewForm()

        context['contact'] = ContactForm()

        context['trips'] = []

        return context
    
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        # Check if the organizer is active
        if (obj.user.is_active == False) or (obj.published == False):
            return redirect('mainapp:home')
        
        obj.views = obj.views + 1
        obj.save()

        context = self.get_context_data()

        return render(request, self.template_name, context)

    def redirect_to_self(self):
        # Redirects the current view back to the save page
        return redirect(reverse('events:event-detail', kwargs={'slug': str(self.get_object().slug)}))
    
    def post(self, request, *args, **kwargs):
        request = self.request
        context = self.get_context_data()

        # Check if the user is authenticated
        if not request.user.is_authenticated:
            messages.warning(request, f'Kindly login your account or create a new account with the Login/Sign up button below')
            return redirect('mainapp:home')
        
        # Identify the form submitted
        submit = request.POST.get('submit')

        event = self.get_object()

        if submit == 'buy_ticket':
            ticket_errors = []
            ticket_infomation = []
            # Validate submited form

            info_tools = event.get_tools_dict()
            post = request.POST

            for fobj in info_tools:
                # Get the field
                label = fobj['name']
                name = fobj['form_name']
                info = post.get(name)

                d_info = {label:info}

                if name == 'line_up':
                    names = ['first', 'second', 'third', 'fourth']

                    d_info = {'line_up': []}

                    for i in names:
                        datax = post.get(i)
                        dataxi = post.get(f'{i}_line')

                        dataxi = 'Yes' if dataxi == 'on' else ''

                        data_obj = {
                            i.capitalize() : datax,
                            'captain': dataxi
                        }

                        d_info['line_up'].append(data_obj)

                elif fobj['included_required'] == '11':
                    if not info:
                        ticket_errors.append(f'{label} is required')
                        continue

                # Add information to ticket information
                ticket_infomation.append(d_info)

            if len(ticket_errors) == 0:

events/templates/events/my_events.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block contents %}
	<!-- Page Header -->
	<section id="et-pagehead" class="container-fluid text-center text-white img-overlay no-hover position-relative pt-5 pb-5">
		<div class="container position-relative pt-5 pb-5 mt-5 mb-5">
            {% if custom_title %}
			<h1 class="box-heading mb-5 position-relative mb-0 text-white">{{ custom_title }}</h1>
            {% else %}
			<h1 class="box-heading mb-5 position-relative mb-0 text-white">My Events</h1>
            {% endif %}
		</div>
		<div class="breadcrumb position-absolute text-center m-0 justify-content-center bg-transparent text-white">
			<a href="/" class="text-white d-inline-block p-2">Home</a>
			<a href="{% url 'events:event-search' %}" class="text-white d-inline-block p-2">Events</a>
			<a href="" class="text-white d-inline-block p-2">{{ title }}</a>
		</div>
	</section>

	<!-- Filter -->
	<div id="et-filter-row" class="container-fluid pt-3 pb-3 bg-primary text-white">
		<div class="container">
			<div class="d-flex align-items-center">
				<div class="d-flex mb-3 mb-sm-0 align-items-center">
					<p class="small m-0 text-white">Events ({{events.count}} results)</p>
				</div>
				<!-- <div class="ml-auto d-flex align-items-center">
					<label class="pr-3 mb-0">Sort: </label>
					<select class="bg-white form-control pb-0 pt-0 pl-4 mb-0" name="sort">
						<option value="most_viewed">Most Viewed</option>
						<option value="most_recent">Most Recent</option>
						<option value="most_liked">Most Liked</option>
					</select>
				</div> -->
			</div>
		</div>
	</div>

	<!-- Content section -->
	<section id="et-events-area" class="container-fluid pt-4">
		<div class="container">
			<div class="row">
                {% if events.count == 0 %}
                <div class="col-md-6 mt-3 mb-3">
                    <h2 class="my-5">No Events Here Yet</h2>
                </div>
                {% endif %}
                {% for i in events %}
                    <div class="col-md-6 mt-3 mb-3">
                        <div class="blog-grid w-100 mt-4 rounded shadow" style="min-width: 400px;">
                            <div class="image-wrap position-relative">
                                <!-- <span class="badge badge-primary listings photocount position-absolute">110 Listings</span> -->
                                <img src="{{ i.featured_image.url }}" alt="img" class="img-fluid rounded-top event-featured-image">
                            </div>
                            <div class="content p-4">
                                <span class="text-muted"><i class="icon-clock text-primary"></i> &nbsp;Posted {{ i.days_since_created }}</span>
                                <span class="text-primary float-right">{{ i.price_val }}</span>
                                <hr>
                                <h4 class="mb-3"><a href="{% url 'events:event-detail' i.slug %}" class="text-decoration-none text-reset">{{ i.title }}</a></h4>
                                <p class="description">
                                    {{ i.description | safe | truncatechars:30 }}
                                </p>
                                <div class="info">
                                    <div class="mb-2"><i class="icon-clock"></i>&nbsp; {{ i.start_date|date:"d M Y" }} - {{ i.end_date|date:"d M Y" }}</div>
                                    <div class="mb-2"><i class="icon-contact"></i>&nbsp; {{ i.email }}</div>
                                    <div><i class="icon-phone"></i>&nbsp; {{ i.phone }}</div>
                                </div>
                                <hr>

                                <div class="d-flex justify-content-between">
                                    <div class="time-left mt-4 d-inline-block pt-2 pt-md-0" end_date = "{{ i.end_date_js_format }}">
                                        <div class="timer search">
                                            <div class="days"></div>
                                            <div class="hours text-primary-flat"></div>
                                            <div class="minutes text-secondary-flat"></div>
                                            <div class="seconds"></div>
                                        </div>
                                    </div>
                                {% if request.user == i.user %}

                                
                                    <div class="d-flex">
                                        <a href="{% url 'events:event-update' i.uid %}" class="position-relative float-right border-0 mt-3 btn btn-primary btn-small submit-btn">
                                            <i class="icon-calendar btn-icon input-icon"></i> Edit
                                            <input type="submit" class="h-100 w-100 position-absolute" value="Discover Now">
                                        </a>

                                        <a href="{% url 'events:event-duplicate' i.uid %}" class="position-relative float-right border-0 mt-3 btn btn-primary btn-small submit-btn">
                                            <i class="icon-calendar btn-icon input-icon"></i> Duplicate
                                            <input type="submit" class="h-100 w-100 position-absolute" value="Discover Now">
                                        </a>
                                    </div>
                                

                                {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
			</div>
            {% if page_obj %}
            <div class="pagination">
                <div style="margin-left: auto;" class="pagination">
                {% if page_obj.has_previous %}
                    <a class="badge badge-secondary" href="?page=1">First</a>
                    <a class="badge badge-secondary" href="?page={{page_obj.previous_page_number}}">Previous</a>
                {% endif%}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <a class="badge badge-primary" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="badge badge-secondary" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="badge badge-secondary" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="badge badge-secondary" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif%}
                </div>
            </div>
            {% endif %}
		</div>
	</section>

	{% include 'mainapp/auth_modals.html' %}
{% endblock %}

events/templates/events/registered_teams.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load mytags %}

{% block contents %}
	<!-- Page Header -->
	<section id="et-pagehead" class="container-fluid text-center text-white img-overlay no-hover position-relative pt-5 pb-5">
		<div class="container position-relative pt-5 pb-5 mt-5 mb-5">
			<h1 class="box-heading mb-5 position-relative mb-0 text-white">Registered Teams</h1>
		</div>
		<div class="breadcrumb position-absolute text-center m-0 justify-content-center bg-transparent text-white">
			<a href="/" class="text-white d-inline-block p-2">Home</a>
			<a href="{% url 'account:profile'%}" class="text-white d-inline-block p-2">Profile</a>
			<a href="" class="text-white d-inline-block p-2">Registered Teams</a>
		</div>
	</section>

	<!-- Filter -->
	<div id="et-filter-row" class="container-fluid pt-3 pb-3 bg-primary text-white">
		<div class="container">
			<div class="d-flex align-items-center">
				<div class="d-flex mb-3 mb-sm-0 align-items-center">
					<h5 class="small m-0 pr-2 d-none d-md-block text-white">Registered Teams:</h5> <p class="small m-0 text-white"> ({{ tickets.count }})</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Content section -->
	<section id="et-calendar-area" class="container-fluid pt-4">
		<div class="container">
			<div class="row justify-content-center">

				<!-- Listing Result -->
                {% for event in events %}

	                
						<div class="col-md-7 my-5 mt-md-0">
							<div class=" scrollbar-inner bg-white shadow overflow-auto">
								
								<div class="event ticket-box d-block text-decoration-none text-reset registered-team-box">
									
									<div class="d-flex p-3 head-x">
										<h3 class="mr-auto"><a href="{% url 'events:event-detail' event.slug %}" class="text-dark">{{ event.title.capitalize }}</a></h3>
										<span class="pl-3"><i class="icon-clock text-white"></i> {{ event.start_date|date:"d M"}} - {{ event.end_date|date:"d M"}}</span>
									</div>
									
									<div class="tickets-cont">
										{% for i in event.userticket_set.all %}
											{% if i.information %}
												<div class="pt-3 reg_list_item" paid="{{ i.is_paid }}">
													{% return_html i.get_info_dict %}
												</div>
											{% endif %}
										{% endfor %}
									</div>

									{% if not event.userticket_set.all %}
										<div class="p-3">
											<h3>No Registered Teams</h3>
										</div>
									{% else %}
										<!-- <div class="p-3 d-flex align-items-center">
											<p>Filter by: </p>
											<p>Paid <input type="radio" name="radx-{{ event.id }}" class="payment_radio" value="paid"></p>
											<p>Not Paid <input type="radio" name="radx-{{ event.id }}" class="payment_radio" value="not_paid"></p>
										</div> -->
									{% endif %}
								</div>
								
							</div>
						</div>
					

                {% endfor %}
			</div>
		</div>
	</section>

	{% include 'mainapp/auth_modals.html' %}
{% endblock %}

events/templates/events/search-map-right.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block contents %}
	<!-- Content section -->
	<section id="et-search-event" class="container-fluid pt-0">
		<div class="row m-0">

			<!-- Search Area -->
			<form method="get" autocomplete="off" class="form col-lg-12 p-0">
				<!-- Filter -->
				<div id="et-filter-row" class="container-fluid pt-3 pb-3 bg-primary text-white">
					<div class="container">
						<div class="d-sm-flex align-items-center">
							<div class="d-flex mb-3 mb-sm-0 align-items-center">
								<h5 class="small m-0 pr-2 d-none d-md-block text-white">Search result(s) for:</h5> <p class="small m-0">Events nearby ({{ events.count }} results)</p>
							</div>
							<div class="ml-auto d-flex align-items-center">
								<label class="pr-3 mb-0">Sort: </label>
								<select id="sort_selector" class="bg-white form-control pb-0 pt-0 pl-4 mb-0" name="sort">
									<option value="most_viewed">Most Viewed</option>
									<option value="most_recent">Most Recent</option>
									<option value="most_liked">Most Liked</option>
								</select>
								<div class="ml-auto">
									<!-- <span id="event-grid-view" class="p-2 ml-auto"><i class="icon-menu pointer"></i></span> -->
									<!-- <span id="event-list-view" class="p-2 ml-auto"><i class="icon-list pointer"></i></span> -->
									<span id="toggle-filter" class="p-2 ml-auto"><i class="fas fa-filter pointer"></i></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Form -->
				<div class="search-filter pl-4 pr-4">
					<!-- <form class="form" method="get" autocomplete="off"> -->
						<div class="row mt-3">
							<div class="col-md-6">

								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<div class="input-group">
												<input list='title_list' id="search-tcd" name='search-tcd' placeholder="Search by Title / Description" class="form-control bg-light" type="text" value="{% if search_tcd %}{{ search_tcd }}{% endif %}">
												<div class="input-group-append">
													<a href="#" class="input-group-text text-decoration-none transition bg-primary border-0 text-white">
														<i class="icon-search-2"></i>
													</a>
												</div>
											</div>

											<datalist id='title_list'>
												
											</datalist>

										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<div class="input-group">
												<input id="searchInput" name='search-input' placeholder="Search by Location" class="form-control bg-light" type="text" value="{% if searchInput %}{{ searchInput }}{% endif %}">
												<div class="input-group-append">
													<a href="#" class="input-group-text text-decoration-none transition bg-primary border-0 text-white">
														<i class="icon-compass"></i>
													</a>
												</div>
											</div>

											<div id="map"></div>

										</div>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<select class="bg-light form-control wide w-100 pb-0 pt-0 pl-4 mb-3 mb-md-0" name="category">
												<option value="">Select Region</option>
												{% for i in category %}
												<option value="{{ i.id }}" {% if searchCategory %}{% if searchCategory == i.id %}selected{% endif %}{% endif %}>{{ i.name }}</option>
												{% endfor %}
											</select>
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<div class="form-group position-relative">
												<input name="start_time" size="16" type="text" placeholder="From" readonly class="form-control bg-light form_datetime" value="{{ start_time }}">
												<i class="icon-clock input-icon"></i>
											</div>
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<div class="form-group position-relative">
												<input name="end_time" size="16" type="text" placeholder="To" readonly class="form-control bg-light form_datetime" value="{{ end_time }}">
												<i class="icon-clock input-icon"></i>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>


						<!-- <div class="row">
							<div class="col">
								<div class="form-group">
									<label>Price Range:</label>
									<input type="text" class="js-range-slider" name="price_range" value="" />
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									<label>Radius(KM):</label>
									<input type="text" class="js-range-slider" name="radius" value="" />
								</div>
							</div>
						</div> -->
						<div class="row justify-content-end pb-3">
							<div class="col-6 d-flex justify-content-end">
								<div class="position-relative border-0 mt-md-0 mt-3 btn btn-primary submit-btn">
									<i class="icon-tick btn-icon input-icon"></i> Search
									<input id="filterFormSubmit" name='search' type="submit" class="h-100 w-100 position-absolute" value="Submit">
								</div>
								{% if request.GET.search %}
								<a href="{% url 'events:event-search' %}" class="btn btn-primary ml-3">X Remove filter</a>
								{% endif %}
							</div>
						</div>
					<!-- </form> -->
				</div>

				<!-- Events -->
				<div class="event-results pl-4 pr-md-4">
					{% if events.count == 0 %}
					<h3 class="text-center">No results found</h3>
					{% endif %}
					<!-- Grid View -->
					<div class="row grid-view scrollbar-inner scroll-content">
						{% for i in events %}
						<div class="col-md-6 mt-3 mb-3">
							<div class="blog-grid w-100 mt-4 rounded shadow" style="min-width: 400px;">
								<div class="image-wrap position-relative">
									<img src="{{ i.featured_image.url }}" alt="img" class="img-fluid rounded-top event-featured-image">

									<span class="badge badge-primary region_loc position-absolute">{{ i.category.name }}</a>
								</div>
								<div class="content p-4">
									<span class="text-muted"><i class="icon-clock text-primary"></i> &nbsp;Posted {{ i.days_since_created }}</span>
									<span class="text-primary float-right">{{ i.price_val }}</span>
									<hr>
									<h4 class="mb-3"><a href="{% url 'events:event-detail' i.slug %}" class="text-decoration-none text-reset">{{ i.title }}</a></h4>
									<p class="description">
										{{ i.description | safe | truncatechars:30}}
									</p>
									<div class="info">
										<div class="mb-2"><i class="icon-clock"></i>&nbsp; {{ i.start_date|date:"d M Y" }} - {{ i.end_date|date:"d M Y" }}</div>
										<div class="mb-2"><i class="icon-contact"></i>&nbsp; {{ i.email }}</div>
										<div><i class="icon-phone"></i>&nbsp; {{ i.phone }}</div>
									</div>
									<hr>
									<div class="time-left mt-4 d-inline-block pt-2 pt-md-0" end_date = "{{ i.end_date_js_format }}">
										<div class="timer search">
											<div class="days"></div>
											<div class="hours text-primary-flat"></div>
											<div class="minutes text-secondary-flat"></div>
											<div class="seconds"></div>
										</div>
									</div>
									<a href="{% url 'events:add-calendar' i.uid %}" class="position-relative float-right border-0 mt-3 btn btn-primary btn-small submit-btn">
										<i class="icon-calendar btn-icon input-icon"></i> Register
										<input type="submit" class="h-100 w-100 position-absolute" value="Discover Now">
									</a>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</form>
			<!-- Map Division -->
			<div class="col-lg-4 p-0 d-none">
				<div class="search-map h-100">
					<div id="map"  class="w-100 h-100"></div>
				</div>
			</div>
		</div>
	</section>

	{% include 'mainapp/auth_modals.html' %}
{% endblock contents %}