account/urls.py
from django.urls import path

from . import views


app_name='account'
urlpatterns = [
    path('logout/', views.Logout, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
    path('submit-newsletter-form/', views.newletter_submit, name='newsletter-submit'),
    
    path("activate/<slug:uidb64>/<slug:token>/", views.activate_email, name="activate"),

    path('reset/<uidb64>/<token>/', views.ResetPasswordVerify.as_view(), name='password_reset_confirm'),

]

boni/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('mainapp.urls')),
    path('events/', include('events.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views


app_name='events'
urlpatterns = [
    path('add/', views.CreateEvent.as_view(), name='add-event'),
    path('edit/<str:uid>/', views.UpdateEvent.as_view(), name='event-update'),
    path('duplicate/<str:uid>/', views.duplicate_event, name='event-duplicate'),
    path('detail/<str:slug>/', views.EventDetail.as_view(), name='event-detail'),
    
    path('search/', views.EventSearch.as_view(), name='event-search'),
    path('calendar/', views.EventCalendarView.as_view(), name='event-calendar'),
    path('my-events/', views.MyEvent.as_view(), name='my-event'),
    path('add-calendar/<str:uid>/', views.add_event_to_calendar, name='add-calendar'),
    path('events/organizer/<str:uid>/', views.OrganizerEvents.as_view(), name='organizer-events'),
    # path('events/my_tickets/', views.UserEventTickets.as_view(), name='my-tickets'),
    # path('order/tickets/<str:uid>', views.order_ticket, name='order-ticket'),

    path('save/<str:uid>/', views.add_event_to_saved, name='save-event'),
    path('saved/', views.SavedEvents.as_view(), name='saved-events'),
    # path('report/<str:uid>/', views.report_event_now, name='report-events'),

    path('events/registered_teams/', views.RegisteredTeams.as_view(), name='registered-teams'),
    
    path('trip_advisor/', views.get_trips_view, name='trip-advisor'),

]

mainapp/urls.py
from django.urls import path

from . import views


app_name='mainapp'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),

    # Ajax url for getting news
    path('facebook_news/', views.get_news_view, name='facebook_url')
]

mainapp/models.py
from django.db import models

# Create your models here.


class HomeLocation(models.Model):
	name = models.CharField(max_length=255)
	image = models.ImageField(upload_to='home_locations/')

	def __str__(self):
		return self.name

	def get_name(self):
		return self.name.replace('-', ' ')

class HomeBackground(models.Model):
	image = models.ImageField(upload_to='home_background/')

	def __str__(self):
		return self.image.name

mainapp/views.py
import random

from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import logout,authenticate,login
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.utils.encoding import force_text,force_bytes
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.http import JsonResponse
from django.core.paginator import Paginator

from account.models import User
from account.forms import (UserRegisterForm, LoginForm, ChangePasswordForm,
    ResetPasswordValidateEmailForm, ForgetPasswordForm)
from account.tokens import acount_confirm_token

from events.models import Category, Event, FeaturedLocation, Gallery
from events.utils import get_fb_posts

from .mixins import ajax_autocomplete
from .models import HomeLocation, HomeBackground


def verification_message(request, user, template):
	site=get_current_site(request)
	uid=urlsafe_base64_encode(force_bytes(user.pk))
	token=acount_confirm_token.make_token(user)
	message=render_to_string(template,{
		"user": user.profile.username,
		"uid": uid,
		"token": token,
		"domain": site.domain,
		'from': settings.DEFAULT_FROM_EMAIL
	})
	return message

def send_verification(user, request):
    site=get_current_site(request)
    uid=urlsafe_base64_encode(force_bytes(user.pk))
    token=acount_confirm_token.make_token(user)

    subject = f"Bonspiels Email Verification"
    message = verification_message(request, user, "account/activation_email.html")

    return user.email_user(subject,message)

def get_news_view(request):
    if request.is_ajax():
        # Get the news
        news = get_fb_posts()

        return JsonResponse(data={'results': news}, status=200)

    return redirect('mainapp:home')

class Home(TemplateView):
    template_name = 'mainapp/index.html'
    extra_context = {
    }

    form_class = LoginForm
    register_form = UserRegisterForm
    reset_form = ResetPasswordValidateEmailForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = Event.objects.filter(user__active=True, published=True).get_current_events()
        categories_set = Category.objects.all()
        

        # Sending the form to the template
        context['form'] = self.form_class()
        context['reg_form'] = self.register_form()
        context['reg_form'] = self.reset_form()

        context['events'] = queryset[:5]

        # Send sets to context
        context['all_events'] = queryset
        context['all_categories'] = categories_set

        # Get featured and upcoming events (4)
        context['featured_events'] = queryset.filter(featured=True)[:2]
        context['upcoming_events'] = queryset.get_upcoming()[:2]

        print(context['upcoming_events'], len(context['upcoming_events']))

        # Get the icon locations
        context['loc_icons'] = HomeLocation.objects.all()

        # Get background images for home
        context['bgs_hero'] = HomeBackground.objects.all()

        # Get the events by location
        locations = FeaturedLocation.objects.all()

        # Paginate the locations by four
        location_page_obj = Paginator(locations, 4)

        # Add the object list of all pages into a list
        location_page_list = []

        for i in location_page_obj.page_range:
            location_page_list.append(location_page_obj.page(i).object_list)

        context['location_page_list'] = location_page_list

        return context
    

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()

        response = ajax_autocomplete(request, context)
        if response is not None:
            return response

        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        request = self.request
        context = self.get_context_data()

        # Know which form was sent to decide the processing
        submit = request.POST.get('submit')

        if submit == 'login':
            form = self.form_class(request.POST)
            if form.is_valid():
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')

                user = authenticate(request, username=email, password=password)
                if user:
                    login(request, user)
                    messages.success(request, f'Welcome, {user.profile.username}')
                else:
                    # Send email verification link to user
                    user = User.objects.get(email=email)
                    send_verification(user, request)
                    messages.success(request, f'A link was sent to your email {user.email}, use the link to verify you account.')
                
                return redirect('mainapp:home')
            else:
                messages.warning(request, 'Please correct your email / password.')
                context['form'] = form

        elif submit == 'register':
            form = self.register_form(request.POST)
            if form.is_valid():
                user = form.save()
                
                # Send email verification link to user
                send_verification(user, request)
                messages.success(request, f'You account is successfully created. A link was sent to your email {user.email}, use the link to verify you account.')
                return redirect('mainapp:home')
            else:
                messages.warning(request, 'Registration form is not valid')
                context['reg_form'] = form
        
        elif submit == 'reset':
            form = self.reset_form(request.POST)
            if form.is_valid():
                email = form.cleaned_data.get('email')
                user = User.objects.get(email=email)

                # Send the reset link to user
                subject = "Bonspiels Password Reset"
                message = verification_message(request, user, "account/password_reset.html")
                user.email_user(subject, message)
            
            print(form.errors)

            messages.success(request, 'A password reset link has been sent to your email if it is registered, click on the link to reset your password')
            return redirect('mainapp:home')
        
        return render(request, self.template_name, context)


class About(TemplateView):
    template_name = 'mainapp/about.html'
    extra_context = {
        'title': 'About Us',
    }


class Contact(TemplateView):
    template_name = 'mainapp/contact.html'
    extra_context = {
        'title': 'Contact Us',
    }

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">


<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="Exact Themes">

    {% if title %}
	    <title>Bonspiels - {{ title }}</title>
    {% else %}
	    <title>Bonspiels</title>
    {% endif %}
    

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" href="{% static 'css/icons.css' %}">

	<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/colors.css' %}">
	<link rel="stylesheet" href="{% static 'css/typography.css' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

	<link rel="stylesheet" href="{% static 'css/hc-offcanvas-nav.css' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.scrollbar/0.2.10/jquery.scrollbar.css">
	<link rel="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css">

	<!-- Bootstrap DateTimePicker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}"/>
	<!-- jQuery Nice Select -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"/>

	<!-- Plugin CSS file with desired skin -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css"/>

	<!-- Plugin CSS file with desired skin -->
	<link rel="stylesheet" href="{% static 'css/jquery.mswitch.css' %}"/>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155204293-2"></script>
	<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', 'UA-155204293-2');
	</script>
</head>
<body class="home">

	{% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
        {% endfor %}
    {% endif %}

	<!-- Navbar -->
	<nav class="et-navbar navbar">
		<a class="logo h6 mb-0" href="{% url 'mainapp:home' %}"><img src="{% static 'img/logo.png' %}" alt="img"></a>
		<ul class="nostyle nav-links inline mr-lg-auto text-right text-lg-left flex-lg-grow-1 mb-0">
			<li class="dropdown">
				<a href="{% url 'mainapp:home' %}">Home</a>
			</li>
			
			<!-- <li class="dropdown">
				<a href="{% url 'account:profile' %}">Profile</a>
			</li> -->

			<li class="dropdown">
				<a href="{% url 'events:event-search' %}">Search</a>
			</li>

			<!-- <li class="dropdown">
				<a href="#">Events</a>
				<ul class="submenu shadow">
					<li><a href="{% url 'events:add-event' %}">Add Events</a></li>
					<li><a href="{% url 'events:my-event' %}">My Events</a></li>
					<li><a href="{% url 'events:saved-events' %}">My Saved Events</a></li>
					<li><a href="{% url 'events:event-calendar' %}">Event Calendar</a></li>
				</ul>
			</li> -->


			<li><a href="{% url 'mainapp:about' %}">About</a></li>
			<li class="dropdown">
				<a href="{% url 'mainapp:contact' %}">Contact</a>
			</li>

		</ul>
		<div class="nav-actions ml-auto">
			<a href="{% url 'account:profile' %}"><i class="icon-user"></i> {{ request.user.email }}</a>
			{% if request.user.is_authenticated %}
				<a href="{% url 'account:logout' %}" style="color: red;"><i class="icon-login"></i> Logout</a>
			{% else %}
				<a href="#" data-toggle="modal" data-target="#exampleModal"><i class="icon-login"></i> Login/Signup</a>
			{% endif %}
			
			<a href="{% url 'events:add-event' %}" class="btn btn-primary border-0"><i class="icon-plus btn-icon"></i> Add Event</a>
		</div>
	</nav>

	<!-- Mobile Menu -->
	<nav id="et-mobile-nav">
		<ul class="text-capitalize">
			<li>
				<a href="{% url 'mainapp:home' %}">Home</a>
			</li>
			<li><a href="{% url 'mainapp:about' %}">About</a></li>
	
			<li>
				<a href="{% url 'account:profile' %}">Profile</a>
				
			</li>
			<li>
				<a href="#">Events</a>
				<ul class="submenu shadow">
					<li><a href="{% url 'events:add-event' %}">Add Events</a></li>
					<li><a href="{% url 'events:my-event' %}">My Events</a></li>
					<li><a href="{% url 'events:saved-events' %}">My Saved Events</a></li>
					<li><a href="{% url 'events:event-calendar' %}">Event Calendar</a></li>
				</ul>
			</li>
		
			<li><a href="{% url 'mainapp:contact' %}">Contact</a></li>
		</ul>
	</nav>

    
    {% block contents %}
        
    {% endblock contents %}
        

    {% if not request.user.is_authenticated %}
	<!-- Subscribe -->
	<section id="et-subscribe-form">
		<div class="box-wrap img-overlay no-hover position-relative rounded shadow p-5 text-white">
			<div class="container position-relative">
				<h4 class="text-white">Get The Best Of All Hands Delivered To Your Inbox</h4>
				<p>Subscribe to our newsletter and stay updated.</p>
				<form method="POST" action="{% url 'account:newsletter-submit' %}" class="d-md-flex">
					{% csrf_token %}
					<input name="email" type="email" class="form-control text-white mr-3 bg-transparent border-bottom d-inline-block subinput rounded-0" placeholder="Enter your email">
					<div class="position-relative border-0 mt-md-0 mt-3 btn bg-white submit-btn">
						<i class="icon-login btn-icon input-icon"></i> Subscribe
						<input type="submit" class="h-100 w-100 position-absolute" value="Discover Now">
					</div>
				</form>
			</div>
		</div>
	</section>
	{% endif %}

	<footer id="et-site-footer" class="container-fluid position-relative bg-footer text-white pt-5 pb-2">
		<div class="container">
			<div class="row">
				<!--About-->
				<div class="col-md-3 about widget">
					<a class="logo h6 mb-0 text-decoration-none text-white" href="#"><img src="{% static 'img/logo-footer.png' %}" alt="img"> Bonspiels</a>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
					<ul class="social nostyle inline text-white p-0">
						<li class="mr-2"><a href="#" class="text-white d-block text-decoration-none transition"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
						<li class="mr-2"><a href="#" class="text-white d-block text-decoration-none transition"><i class="fab fa-google" aria-hidden="true"></i></a></li>
						<li class="mr-2"><a href="#" class="text-white d-block text-decoration-none transition"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
						<li class="mr-2"><a href="#" class="text-white d-block text-decoration-none transition"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
						<li class="mr-2"><a href="#" class="text-white d-block text-decoration-none transition"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<!--Contact-->
				<div class="col-md-3 contact widget">
					<h5 class="text-white">Contact Us</h5>
					<ul class="nostyle text-white p-0">
						<li class="mt-4 d-block"><i class="fas fa-envelope"></i>&nbsp; info@bonspiels.com</li>
						<li class="mt-4 d-block"><i class="fas fa-phone-alt"></i>&nbsp; (888)000-000 - 000</li>
						<li class="mt-4 d-block"><i class="fas fa-map-marker-alt"></i>&nbsp;BD land, P.O. Box 0000, Demo, TX 00000-0000</li>
					</ul>
				</div>
				<!--Navigation-->
				<div class="col-md-3 navigation widget">
					<h5 class="text-white">Navigation</h5>
					<ul class="nostyle text-white p-0">
						<li class="mt-4 d-block"><a href="{% url 'mainapp:home' %}">Home</a></li>
						<li class="mt-4 d-block"><a href="{% url 'mainapp:about' %}">About us</a></li>
						<li class="mt-4 d-block"><a href="#">What We Do</a></li>
						<li class="mt-4 d-block"><a href="#">Privacy Policy</a></li>
					</ul>
				</div>

				<!--Navigation-->
				<div class="col-md-3 navigation widget">
					<h5 class="text-white">Navigation</h5>
					<ul class="nostyle text-white p-0">
						<li class="mt-4 d-block"><a href="#">Terms & conditions</a></li>
						<li class="mt-4 d-block"><a href="#">Privacy policy</a></li>
						<li class="mt-4 d-block"><a href="#">Cookies policy</a></li>
						<li class="mt-4 d-block"><a href="#">Copyrights Policy</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<div class="et-bottom-bar pt-2 pb-2">
		<div class="container">
			<div class="row justify-content-md-left justify-content-center align-items-center">
				<div class="partners">
					
				</div>
				<div class="ml-sm-auto mt-3 mt-sm-0">
					<p class="mb-0">Copyright © 2021 - <a class="text-decoration-none text-reset" href="#">Codecell ltd</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="et-preloader"><div></div><div></div></div>

	<!-- Scripts -->
	<script src="{% static 'js/bg-slider.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.1/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
	<script src="{% static 'js/hc-offcanvas-nav.js' %}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	
	<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>

	<!--Ion Range Slider-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>
	<!--Toggle Switcher -->
	<script src="{% static 'js/jquery.mswitch.js' %}"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.scrollbar/0.2.10/jquery.scrollbar.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>

	<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>


	<script src="{% static 'js/custom.js' %}"></script>

	
	<!-- <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyB8AWIQyXO0kFl4_zD3dEk21BPaz08WBmA&libraries=places&ver=1.1'></script> -->
	<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyB8AWIQyXO0kFl4_zD3dEk21BPaz08WBmA&callback=initMap"></script>

</body>


</html>

mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block contents %}

	<!-- Page Header -->
	<section id="et-pagehead" class="container-fluid text-center text-white img-overlay no-hover position-relative pt-5 pb-5">
		<div class="container position-relative pt-5 pb-5 mt-5 mb-5">
			<h1 class="box-heading mb-5 position-relative mb-0 text-white">Contact Us</h1>
		</div>
		<div class="breadcrumb position-absolute text-center m-0 justify-content-center bg-transparent text-white">
			<a href="#" class="text-white d-inline-block p-2">Home</a>
			<a href="#" class="text-white d-inline-block p-2">Contact us</a>
		</div>
	</section>

	<!-- Content Area -->
	<section id="et-content" class="container-fluid">
		<div class="container">
			<!-- Contact info -->
			<div class="row">
				<div class="col-lg-4">
					<div class="bg-white boxhover transition pt-5 pb-5 shadow d-flex align-items-center justify-content-center">
						<i class="icon-clock text-primary h1 m-0"></i>
						<div class="pl-4">
							<h6>Monday - Friday</h6>
							<p class="m-0">Office hours</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="bg-white boxhover transition pt-5 pb-5 shadow d-flex align-items-center justify-content-center">
						<i class="icon-contact text-primary h1 m-0"></i>
						<div class="pl-4">
							<h6>business@bonspiels.net</h6>
							<p class="m-0">Business email</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="bg-white boxhover transition pt-5 pb-5 shadow d-flex align-items-center justify-content-center">
						<i class="icon-phone text-primary h1 m-0"></i>
						<div class="pl-4">
							<h6>+00 000 00 00</h6>
							<p class="m-0">Toll free</p>
						</div>
					</div>
				</div>
			</div>

			<!-- Map -->
			<div class="et-contact-map mt-5">
				<div id="loadmaps" class="w-100 mb-3"></div>
			</div>

			<!-- Contact form -->
			<div class="et-contact-form mt-5">
				<h5>Drop a message</h5>
				<p class="description mb-4">Please fill this form. We usually reply back within same day</p>
				<form autocomplete="off">
					<div class="row">
						<div class="form-group col-sm-6">
							<input type="text" class="form-control bg-light" placeholder="Name" name="name">
						</div>
						<div class="form-group col-sm-6">
							<input type="email" class="form-control bg-light" placeholder="Email" name="email">
						</div>
						<div class="form-group col-sm-6">
							<input type="text" class="form-control bg-light" placeholder="Phone" name="phone">
						</div>
						<div class="form-group col-sm-6">
							<input type="text" class="form-control bg-light" placeholder="Subject" name="subject">
						</div>
						<div class="form-group col-sm-12">
							<textarea rows="6" class="form-control resize-none bg-light" placeholder="Type your message" name="message"></textarea>
						</div>
					</div>
					<div class="form-group text-center mb-3 mt-4 check-types">
						<label for="cbk1">
							<input type="checkbox" id="cbk1">
							<span class="cbx rounded-pill float-none d-inline-block align-middle">
								<svg width="12px" height="11px" viewBox="0 0 12 11">
									<polyline points="1 6.29411765 4.5 10 11 1"></polyline>
								</svg>
							</span>
							<span class="float-none text-black-50">I agree to the <a href="#" class="text-primary">Terms and conditions</a> and <a href="#" class="text-primary">Privacy policy.</a></span>
						</label>
					</div>
					<div class="text-center">
						<div class="position-relative border-0 mt-md-0 mt-3 btn btn-primary submit-btn">
							<i class="icon-login btn-icon input-icon"></i> Send Email
							<input type="submit" class="h-100 w-100 position-absolute" value="Submit Review">
						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
{% endblock contents %}